### ISSUE TITLE
Test says keydown but should say onChange instead

### ISSUE THREAD

**Issue by gsmith77** [learn-co-curriculum/crud-lab#12]
test is deceiving caused me to do onKeyDown instead of onChange whenever I have never done onKeyDown for my form.

**Comment by maxwellbenton** [comment]
Hi @gsmith77,

Thank you for spotting this and providing feedback. We've updated this lab's test messages to refer to `onChange` rather than keydown, which should resolve this issue.

Thank you for contributing!

**Comment by gsmith77** [comment]
Glad to have helped!!!!!😄
