### ISSUE TITLE
ReadMe is cut off and has a typo

### ISSUE THREAD

**Issue by MaxBrooks114** [learn-co-curriculum/crud-lab#14]
The write up "Start off by working the components for restaurants. First you'll need to create a RestaurantsContainer component that will connect to Redux and pass the appropriate props down to its children. Then you will need a RestaurantInput component that allows a user to create new restaurants. You will then want to create a Restaurants component that displays a list of restaurants, and a Restaurant component which is responsible for each restaurant (and contains the button to delete). Users should also be able to delete restaurants, and to implement that you will need to give each restaurant an id. the" 

That "the" sits on its own

**Comment by maxwellbenton** [comment]
Hi @MaxBrooks114,

We've updated the Readme for this lesson and corrected the errors in this paragraph as well as a few others.

Thank you for spotting this and providing feedback!
