### ISSUE TITLE
Test should be clear about structure of expected redux state

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/crud-lab#25]
A lot of the tests for the reviews are written without any regard to the specific structure of the redux state, but there are a few that specifically expect a top level "reviews" key to store the reviews. We should either make this expectation explicit in the directions, or redo the tests that rely on the redux state being structured this way.

**Comment by lizbur10** [comment]
The README has now been updated to address this issue - thanks @kwebster2 !!
