### ISSUE TITLE
Extra code in ReviewInput.js 

### ISSUE THREAD

**Issue by achasveachas** [learn-co-curriculum/crud-lab#3]
There are a few extra lines of code at the bottm of `src/reviews/ReviewInput.js` that don't seem to belong there and break the tests on startup.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
