### ISSUE TITLE
Test is mislabeled

### ISSUE THREAD

**Issue by mdo5004** [learn-co-curriculum/crud-lab#5]
`reviews-test.js` line 145 reads 

`Reviews Component has a button that dispatches a DELETE_RESTAURANT action with the proper id when clicked:`

but it should read

`Reviews Component has a button that dispatches a DELETE_REVIEW action with the proper id when clicked:`

**Comment by dkStephanos** [comment]
PLEASE ADDRESS THIS!!!!!!!!!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
