### ISSUE TITLE
Minor (but confusing) typos in tests

### ISSUE THREAD

**Issue by breadoliveoilsalt** [learn-co-curriculum/crud-lab#7]
Hi.  Got a little confused by these in test/reviews-test.js:

line 131 - incomplete/awk description --  ```it('has an unique id property that for each element'```

line 145 - description refers to a DELETE_RESTAURANT action, but actual test on line 152 is looking for a DELETE_REVIEW action.

Thanks! Hope a bit helpful...

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @breadoliveoilsalt .

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
