### ISSUE TITLE
Limiting tests

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/crud-lab#8]
Tests do not allow the use of the previously taught DRY pattern: 

`handleChange = e => {
    this.setState({
      [e.target.name]: e.target.value
    })
  }`

Also, the test `sets a property of restaurantId on the review component from the parent components id` should say `review input component` instead of `review component`

**Comment by maxwellbenton** [comment]
Hey @micahshute,

Thanks for this. I've updated the tests to simulate input events with `name` and `id` included so both patterns for `handleChange` will now pass the tests. I've also corrected the typo in the test message.

Thank you!
