### ISSUE TITLE
i.e. instead of i.g.

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/crud-lab#9]
Change "i.g." to "i.e." in the sentence below:
"When sent to your reducer, instead of filtering you might consider mapping - i.g. an action where all reviews are returned, but if a review's id matches, the newly submitted content is returned instead."

Immediately prior to the "i.e.," also change the single dash to a double dash or an em dash.

Thank you.

**Comment by maxwellbenton** [comment]
Fixed! Thank you @ValerieHMoore!
